import './globals.css'
import { Inter } from 'next/font/google'
import Navbar2 from './navbar2'
import Link from 'next/link'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar2/>
        {/* <Footer/> */}
        {children}</body>
    </html>
  )
}
